### ISSUE TITLE
Doesn't log from framework

### ISSUE THREAD

**Issue by dev4jam** [Kofktu/Sniffer#3]
Hi! I have a networking layer as a framework (cocoapod). When I run unittests in this framework project I see all the logs from sniffer class, but if I use this framework in main project it doesn't log at all. I made sure that Sniffer is registered and enabled. Any ideas why?

**Comment by Kofktu** [comment]
@dev4jam 
Is the register normal when used in the main project?
Please refer to [Usage](https://github.com/Kofktu/Sniffer#usage)

**Comment by dev4jam** [comment]
@Kofktu yes, did:

        Sniffer.register()
        Sniffer.enable(in: session.configuration)

**Comment by Kofktu** [comment]
Are you using Alamofire?
If you use Alamofire.SessionManager directly,
you need to activate the configuration separately.
```swift
let configuration = URLSessionConfiguration.`default`
Sniffer.enable(in: configuration)
let sessionManager = Alamofire.SessionManager(configuration: configuration)
```

**Comment by dev4jam** [comment]
I'm using my own networking layer. But very similar to Alamofire.

**Comment by dev4jam** [comment]
![screen shot 2018-07-04 at 3 28 05 pm](https://user-images.githubusercontent.com/34459912/42258405-f0f2792c-7f9e-11e8-89ea-02467be5c7de.png)

**Comment by Kofktu** [comment]
I recommend that you change the way URLSession is generated.

```swift
// AS-IS
public init() {
    session = URLSession.shared
}

// TO-BE
public init() {
    self.init(with: nil)
}

public init(with: delegate: URLSessionDelegate?) {
    let configuration = URLSessionConfiguration.default
   
    // If you want enabled DebugMode
    Sniffer.enable(in: configuration)
    session = URLSession(configuration: configuration, delegate: .., delegateQueue: ..)
}
```

**Comment by dev4jam** [comment]
I can't call Sniffer.enable(in: configuration) right in constructor because it should be controlled outside by calling enableDebugMode() method

**Comment by Kofktu** [comment]
Hmm.. 
How about this?

```swift
private lazy var configuration: URLSessionConfiguration = URLSessionConfiguration.default

public init() {
    self.init(with: nil)
}

public init(with: delegate: URLSessionDelegate?) {
    session = URLSession(configuration: configuration, delegate: .., delegateQueue: ..)
}

public func enabledDebugMode() {
    Sniffer.enable(in: configuration)
}
```

**Comment by dev4jam** [comment]
still the same. no logs

**Comment by dev4jam** [comment]
but it works as is if I just copy all files from framework into the main project :/

**Comment by Kofktu** [comment]
Can you attach a sample project?

**Comment by dev4jam** [comment]
not really... I'll try to create a new minimal project to reproduce this issue

**Comment by dev4jam** [comment]
Noticed that if I use URLSession.shared everything works. But not in case of custom session delegate.

[SnifferTest.zip](https://github.com/Kofktu/Sniffer/files/2164493/SnifferTest.zip)

**Comment by dev4jam** [comment]
@Kofktu any thoughts?

**Comment by Kofktu** [comment]
I've tested it in a variety of ways.
It is not possible to activate `URLSessionConfiguration` after creating `URLSession`.

```swift
private let configuration: URLSessionConfiguration = URLSessionConfiguration.default
private let session: URLSession

public convenience init() {
    self.init(with: nil)
}
    
public init(with delegate: URLSessionDelegate?) {
#if DEBUG
    Sniffer.enable(in: configuration)
#endif
        
session = URLSession(configuration: configuration,
                                        delegate: delegate,
                                        delegateQueue: OperationQueue.main)
}
```

I'm sorry I did not give you a clean answer

**Comment by dev4jam** [comment]
Np. Thanks for support

**Comment by dev4jam** [comment]
it seems it doesn't work with delegates.

**Comment by Kofktu** [comment]
Is not the delegate a nil?
